// Mirrors src/components/CarData.jsx — single source of truth for backend
const CAR_DATA = [
  {
    id: 1,
    name: "Audi A5 S-Line",
    model: "A5",
    mark: "Audi",
    year: "2022",
    doors: "4/5",
    air: true,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDayEth: "0.037",
    available: true,
    seats: 5,
    category: "premium",
  },
  {
    id: 2,
    name: "VW Arteon",
    model: "Arteon",
    mark: "VW",
    year: "2020",
    doors: "4/5",
    air: true,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDayEth: "0.031",
    available: true,
    seats: 5,
    category: "standard",
  },
  {
    id: 3,
    name: "Toyota Corolla",
    model: "Corolla",
    mark: "Toyota",
    year: "2023",
    doors: "4/5",
    air: true,
    transmission: "Automatic",
    fuel: "Hybrid",
    pricePerDayEth: "0.023",
    available: true,
    seats: 5,
    category: "economy",
  },
  {
    id: 4,
    name: "BMW 530",
    model: "530",
    mark: "BMW",
    year: "2022",
    doors: "4/5",
    air: true,
    transmission: "Manual",
    fuel: "Diesel",
    pricePerDayEth: "0.034",
    available: true,
    seats: 5,
    category: "premium",
  },
  {
    id: 5,
    name: "Kia Sportage",
    model: "Sportage",
    mark: "Kia",
    year: "2023",
    doors: "4/5",
    air: true,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDayEth: "0.025",
    available: true,
    seats: 5,
    category: "suv",
  },
  {
    id: 6,
    name: "Mini Cooper",
    model: "Cooper",
    mark: "Mini",
    year: "2020",
    doors: "2/3",
    air: true,
    transmission: "Manual",
    fuel: "Gasoline",
    pricePerDayEth: "0.02",
    available: true,
    seats: 4,
    category: "compact",
  },
];

const LOCATIONS = [
  "Los Angeles",
  "San Diego",
  "Sacramento",
  "San Jose",
  "Long Beach",
];

module.exports = { CAR_DATA, LOCATIONS };
